### ISSUE TITLE
KeyNotFoundException

### ISSUE THREAD

**Issue by StonedModder** [LostSoulfly/SwitchGameManager#1]
`System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.`

I can only assume this is due to my keys.txt being formatted incorrectly. Are you able to provide an example file of what the program searches for? (full of dummy data of course)

**Comment by LostSoulfly** [comment]
Sure, here's the key file outline I have. Could you give more information on the error? It might not be keys related.

```
master_key_00 = AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
master_key_01 = AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
master_key_02 = AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
master_key_03 = AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
master_key_04 = AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA

xci_header_key = AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
header_key = AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
aes_kek_generation_source = AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
aes_key_generation_source = AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
key_area_key_application_source = AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
```

**Comment by StonedModder** [comment]
There we go, that helped! It works now. Thank you.
