### ISSUE TITLE
Renaming Files Doesn't work

### ISSUE THREAD

**Issue by StonedModder** [LostSoulfly/SwitchGameManager#2]
Mass rename on my XCIs seems to not work. Could this be caused by my games already being trimmed?

https://i.imgur.com/nlWQfiO.png

**Comment by LostSoulfly** [comment]
You didn't post the entire window -- did you click the Rename button in the
bottom right corner after setting up the rename filter?

**Comment by StonedModder** [comment]
oof I didn't set up a name filter, I assumed there was one set by default thank you.

I love your application! Keep up the great work!
